export const navItems = [
  //{ to: "Components", icon: "star", label: "Components" },
  { to: "Components/Typeface", icon: "star", label: "Typeface",  },
  { to: "Components/Colors", icon: "star", label: "Color System",},
  { to: "Components/Icons", icon: "star", label: "Icons" },
  { to: "Components/Buttons", icon: "star", label: "Buttons" },
  { to: "Components/CheckboxSwitchers", icon: "star", label: "Checkbox & Switchers" },
  { to: "Components/InputsAndForms", icon: "star", label: "Input & Forms" },
  { to: "Components/CardsAndList", icon: "star", label: "Cards & List",separator:"true", new:"true"  },
  { to: "Components/Layout", icon: "star", label: "Layout & Switches" },
  { to: "Components/Navigation", icon: "star", label: "Navigation & Tabs" },
  { to: "Components/TooltipAndPopover", icon: "star", label: "Tooltip & Popover" },
  { to: "Components/Miscellaneous", icon: "star", label: "Miscellaneous" },
  { to: "Components/Modal", icon: "star", label: "Modal" },
  { to: "Components/Dashboard", icon: "star", label: "Dashboard",separator:"true"  },
  { to: "Components/QuickDemos", icon: "star", label: "Quick Demos",new:"true" },
];