export const navItems = [
  //{ to: "Components", icon: "star", label: "Components" },
  { to: "Typeface", icon: "star", label: "Typeface" },
  { to: "Colors", icon: "star", label: "Color System" },
  { to: "Icons", icon: "star", label: "Icons" },
  { to: "Buttons", icon: "star", label: "Buttons" },
  { to: "CheckboxSwitchers", icon: "star", label: "Checkbox & Switchers" },
  { to: "InputsAndForms", icon: "star", label: "Input & Forms" },
  { to: "CardsAndList", icon: "star", label: "Cards & List" },
  { to: "Layout", icon: "star", label: "Layout & Switches" },
  { to: "Navigation", icon: "star", label: "Navigation & Tabs" },
  { to: "TooltipAndPopover", icon: "star", label: "Tooltip & Popover" },
  { to: "Miscellaneous", icon: "star", label: "Miscellaneous" },
  { to: "Dashboard", icon: "star", label: "Dashboard" },
  { to: "Modal", icon: "star", label: "Modal" },
];