export const BaseColors = [
  { value: "red", name: "Red", description: "A bold brick red, vibrant yet grounded."},
  { value: "pink", name: "Pink", description: "Rich raspberry, lively and elegant."},
  { value: "purple", name: "Purple", description: "Deep iris, luxurious and regal."},
  { value: "amethyst", name: "Amethyst", description: "Majestic violet, bold and striking."},
  { value: "indigo", name: "Indigo", description: "Classic denim, timeless and modern."},
  { value: "blue", name: "Blue", description: "Bright cerulean, crisp and serene."},
 // { value: "light-blue", name: "Ocean Blue", description: "Cool ocean blue, fresh and breezy."},
  { value: "cyan", name: "Cyan", description: "Exotic teal, lively and peacock-like."},
  { value: "teal", name: "Teal", description: "Mystic teal, vibrant and refreshing."},
  { value: "green", name: "Green", description: "Lush fern green, calm and natural."},
  { value: "moss", name: "Moss",  description: "Soft moss green, soothing and earthy.", light:"true"},
  { value: "lime", name: "Lime",  description: "Bright chartreuse, zesty and bold.", light:"true"},
  { value: "yellow", name: "Yellow",  description: "Warm mustard yellow, lively and bold.", light:"true"},
  { value: "amber", name: "Amber",  description: "Rich golden amber, warm and inviting.", light:"true"},
  { value: "orange", name: "Orange", description: "Bright pumpkin orange, bold and fun."},
  { value: "ember", name: "Ember", description: "Intense burnt orange, bold and warm."},
 // { value: "peach", name: "Peach", description: "Soft peach, light and delicate."},
  { value: "brown", name: "Brown", description: "Cocoa brown, warm, cozy, and earthy."},
  { value: "grey", name: "Grey", description: "Neutral slate grey, versatile and cool."},
  { value: "slate", name: "Slate", description: "Stormy blue-grey, elegant and calm."}
];
