export const BaseColors = [
  { value: "red", name: "Red", description: "A bold brick red, vibrant yet grounded.", base: "#e74c3c", light: "#ff867a", lighter: "#ffd1c7", dark: "#b83728", darker: "#4c140b" },
  { value: "pink", name: "Pink", description: "Rich raspberry, lively and elegant.", base: "#d81b60", light: "#ff558b", lighter: "#ffb3cd", dark: "#a0003b", darker: "#3f0014" },
  { value: "purple", name: "Purple", description: "Deep iris, luxurious and regal.", base: "#5e35b1", light: "#9165e5", lighter: "#d8c3ff", dark: "#2e0083", darker: "#0d002a" },
  { value: "amethyst", name: "Amethyst", description: "Majestic violet, bold and striking.", base: "#8e44ad", light: "#c174db", lighter: "#f0c5ff", dark: "#5f297c", darker: "#250f33" },
  { value: "indigo", name: "Indigo", description: "Classic denim, timeless and modern.", base: "#3949ab", light: "#6b75dd", lighter: "#c2caff", dark: "#00217c", darker: "#000a26" },
  { value: "blue", name: "Blue", description: "Bright cerulean, crisp and serene.", base: "#1e88e5", light: "#6bbdff", lighter: "#ccecff", dark: "#005db3", darker: "#00264d" },
  { value: "cyan", name: "Cyan", description: "Exotic teal, lively and peacock-like.", base: "#00acc1", light: "#5fd8ee", lighter: "#c2f8ff", dark: "#007b8f", darker: "#002f38" },
  { value: "teal", name: "Teal", description: "Mystic teal, vibrant and refreshing.", base: "#00897b", light: "#4ebaaa", lighter: "#b3f2e5", dark: "#005b4d", darker: "#00221c" },
  { value: "green", name: "Green", description: "Lush fern green, calm and natural.", base: "#43a047", light: "#76d275", lighter: "#ccffc7", dark: "#00701a", darker: "#002607" },
  { value: "moss", name: "Moss", description: "Soft moss green, soothing and earthy.", light_text: "true", base: "#7cb342", light: "#aee571", lighter: "#e3ffbb", dark: "#4b8300", darker: "#1f3300" },
  { value: "lime", name: "Lime", description: "Bright chartreuse, zesty and bold.", light_text: "true", base: "#c0ca33", light: "#e7ed6c", lighter: "#fcffbf", dark: "#8b9900", darker: "#353900" },
  { value: "yellow", name: "Yellow", description: "Warm mustard yellow, lively and bold.", light_text: "true", base: "#fdd835", light: "#ffe862", lighter: "#fffccc", dark: "#c5a126", darker: "#5a4500" },
  { value: "amber", name: "Amber", description: "Rich golden amber, warm and inviting.", light_text: "true", base: "#ffc53d", light: "#ffe54c", lighter: "#fffcbb", dark: "#d5902c", darker: "#5a3b0d" },
  { value: "orange", name: "Orange", description: "Bright pumpkin orange, bold and fun.", base: "#fb8c00", light: "#ffbd45", lighter: "#ffedc2", dark: "#c25e00", darker: "#5a2600" },
  { value: "ember", name: "Ember", description: "Intense burnt orange, bold and warm.", base: "#f4511e", light: "#ff844c", lighter: "#ffc2aa", dark: "#b91400", darker: "#4a0600" },
  { value: "brown", name: "Brown", description: "Cocoa brown, warm, cozy, and earthy.", base: "#8d6e63", light: "#be9c91", lighter: "#f0dbd5", dark: "#5f4339", darker: "#241610" },
  { value: "grey", name: "Grey", description: "Neutral slate grey, versatile and cool.", base: "#757575", light: "#a4a4a4", lighter: "#e0e0e0", dark: "#494949", darker: "#1c1c1c" },
  { value: "slate", name: "Slate", description: "Stormy blue-grey, elegant and calm.", base: "#546e7a", light: "#819ca9", lighter: "#d5e1e6", dark: "#29434e", darker: "#0d171c" },
];