export const glyphs = [
    { content: "A", primary: "true", large: "true" },
    { content: "B", secondary: "true"  },
    { content: "C" },
    { content: "Č" },
    { content: "Ć" },
    { content: "D" },
    { content: "Đ" },
    { content: "E" },
    { content: "F" },
    { content: "G" },
    { content: "H" },
    { content: "I" },
    { content: "J" },
    { content: "K" },
    { content: "L" },
    { content: "M" },
    { content: "N" },
    { content: "O" },
    { content: "P" },
    { content: "Q" },
    { content: "R" },
    { content: "S" },
    { content: "Š"  },
    { content: "T" },
    { content: "U" },
    { content: "V" },
    { content: "W" },
    { content: "X" },
    { content: "Y" },
    { content: "Z" },
    { content: "Ž" },
    { content: "a" },
    { content: "b" },
    { content: "c" },
    { content: "č" },
    { content: "ć" },
    { content: "d" },
    { content: "đ" },
    { content: "e" },
    { content: "f" },
    { content: "g" },
    { content: "h" },
    { content: "i" },
    { content: "j" },
    { content: "k" },
    { content: "l" },
    { content: "m" },
    { content: "n" },
    { content: "o" },
    { content: "p" },
    { content: "q" },
    { content: "r" },
    { content: "s" },
    { content: "š" },
    { content: "t" },
    { content: "u" },
    { content: "v" },
    { content: "w" },
    { content: "x" },
    { content: "y" },
    { content: "z" },
    { content: "ž" },
    { content: "1", primary: "true", },
    { content: "2" },
    { content: "3" },
    { content: "4" },
    { content: "5" },
    { content: "6" },
    { content: "7" },
    { content: "8" },
    { content: "9" },
    { content: "0" },
    // { content: "?" },
    // { content: "“" },
    // { content: "!" },
    // { content: "”" },
    // { content: "(" },
    // { content: "%" },
    // { content: ")" },
    // { content: "[" },
    // { content: "#" },
    // { content: "]" },
    // { content: "{" },
    // { content: "@" },
    // { content: "}" },
    // { content: "/" },
    // { content: "\\" },
    // { content: "-" },
    // { content: "+" },
    // { content: "÷" },
    // { content: "=" },
    // { content: "&" },
    // { content: "®" },
    // { content: "©" },
    // { content: "$" },
    // { content: "€" },
    // { content: "£" },
    // { content: "¥" },
    // { content: "¢" },
    // { content: ":" },
    // { content: ";" },
    // { content: "," },
    // { content: "." },
    // { content: "*" }
  ];
  